import { defineCollection } from 'astro:content';
import { z } from 'astro/zod';
import { glob } from 'astro/loaders';

const sourceEntry = z.object({
  name: z.string(),
  url: z.string().url(),
  domain: z.string(),
  scrapedAt: z.coerce.date(),
});

const affiliateLink = z.object({
  product: z.string(),
  program: z.string(),
  url: z.string().url(),
});

/**
 * The `articles` collection is the heart of the site: tests + comparatifs +
 * guides generated by packages/scripts/article-generator.js. Schema mirrors
 * the frontmatter contract documented in CLAUDE.md.
 */
const articles = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/articles' }),
  schema: z.object({
    title: z.string().max(70),
    description: z.string().min(120).max(180),
    keyword: z.string(),
    intent: z.enum(['avis', 'comparatif', 'guide', 'informational']),
    publishedAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    heroImage: z.string().optional(),
    heroImageAlt: z.string().optional(),
    sources: z.array(sourceEntry).min(2, 'Min 2 sources for grounding'),
    affiliateLinks: z.array(affiliateLink).default([]),
    groundingScore: z.string().optional(),
    draft: z.boolean().default(false),

    // Extracted from the body's `## FAQ` section by article-generator.js
    // post-pass; consumed by ArticleLayout to emit FAQPage JSON-LD.
    faq: z.array(z.object({ q: z.string(), a: z.string() })).optional(),

    // Test (intent=avis) only
    product: z.object({ name: z.string(), developer: z.string().optional() }).optional(),
    subscores: z.record(z.string(), z.number().min(0).max(10)).optional(),
    weights: z.record(z.string(), z.number().min(0).max(1)).optional(),
    finalScore: z.number().min(0).max(10).optional(),
    pros: z.array(z.string()).optional(),
    cons: z.array(z.string()).optional(),

    // Comparatif (intent=comparatif) only
    products: z
      .array(
        z.object({
          name: z.string(),
          score: z.number().min(0).max(10).optional(),
          program: z.string().optional(),
          asin: z.string().nullable().optional(),
          fallbackUrl: z.string().url().optional(),
          criteria: z.record(z.string(), z.number()).optional(),
        }),
      )
      .optional(),
  }),
});

const page = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/pages' }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    draft: z.boolean().default(false),
  }),
});

export const collections = { articles, page };
