import { defineCollection } from 'astro:content';
import { z } from 'astro/zod';
import { glob } from 'astro/loaders';

const sourceEntry = z.object({
  name: z.string(),
  url: z.string().url(),
  domain: z.string(),
  scrapedAt: z.coerce.date(),
});

const affiliateLink = z.object({
  product: z.string(),
  program: z.string(),
  url: z.string().url(),
});

// Shared product entry — used by both the `articles` (comparatif) collection
// and the hand-authored `satellites` collection so the two stay in lockstep.
const productEntry = z.object({
  name: z.string(),
  score: z.number().min(0).max(10).optional(),
  program: z.string().optional(),
  asin: z.string().nullable().optional(),
  fallbackUrl: z.string().url().optional(),
  merchantUrl: z.string().url().optional(),
  merchant: z.string().optional(),
  price: z.string().optional(),
  image: z.string().optional(),
  criteria: z.record(z.string(), z.union([z.number(), z.string()])).optional(),
});

const faqEntry = z.object({ q: z.string(), a: z.string() });

/**
 * The `articles` collection is the heart of the site: tests + comparatifs +
 * guides generated by packages/scripts/article-generator.js. Schema mirrors
 * the frontmatter contract documented in CLAUDE.md.
 */
const articles = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/articles' }),
  schema: z.object({
    title: z.string().max(70),
    description: z.string().min(120).max(180),
    keyword: z.string(),
    // Secondary keywords from a Semrush cluster (semrush-prioritize.js).
    // Optional — single-keyword articles from the daily DataForSEO pipeline
    // don't carry this field.
    secondaryKeywords: z.array(z.string()).optional(),
    intent: z.enum(['avis', 'comparatif', 'guide', 'informational']),
    publishedAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    heroImage: z.string().optional(),
    heroImageAlt: z.string().optional(),
    sources: z.array(sourceEntry).min(3, 'Min 3 sources for grounding (anti scaled-content-abuse signal — see CLAUDE.md "Anti-spam AI")'),
    affiliateLinks: z.array(affiliateLink).default([]),
    groundingScore: z.string().optional(),
    draft: z.boolean().default(false),
    // Set by article-generator when an `avis` cannot resolve any ASIN from
    // Amazon or Google Shopping — the article publishes without affiliate
    // CTAs instead of failing. Validator branches on this to skip the
    // ≥3 affiliate-button gate.
    noAffiliate: z.boolean().optional(),

    // Extracted from the body's `## FAQ` section by article-generator.js
    // post-pass; consumed by ArticleLayout to emit FAQPage JSON-LD.
    faq: z.array(z.object({ q: z.string(), a: z.string() })).optional(),

    // Test (intent=avis) only
    product: z.object({ name: z.string(), developer: z.string().optional() }).optional(),
    subscores: z.record(z.string(), z.number().min(0).max(10)).optional(),
    weights: z.record(z.string(), z.number().min(0).max(1)).optional(),
    finalScore: z.number().min(0).max(10).optional(),
    pros: z.array(z.string()).optional(),
    cons: z.array(z.string()).optional(),

    // Comparatif (intent=comparatif) only
    products: z
      .array(
        z.object({
          name: z.string(),
          score: z.number().min(0).max(10).optional(),
          program: z.string().optional(),
          asin: z.string().nullable().optional(),
          fallbackUrl: z.string().url().optional(),
          criteria: z.record(z.string(), z.number()).optional(),
        }),
      )
      .optional(),

    // Sibling articles from the same topical bundle (pillar + comparatif +
    // avis, see packages/scripts/lib/bundle.js). Maintained by the generator
    // — each article in the bundle gets the full sibling list re-injected
    // whenever the bundle progresses, so the layout's "Articles liés"
    // section always reflects the current state.
    bundleSiblings: z
      .array(
        z.object({
          slot: z.enum(['comparatif', 'pillar', 'avis']),
          title: z.string(),
          url: z.string().url(),
        }),
      )
      .optional(),
  }),
});

const page = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/pages' }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    draft: z.boolean().default(false),
  }),
});

/**
 * Hub-and-spoke pillar pages (e.g. /solaire/, /exterieur/). Hand-authored,
 * navigable category landing pages — distinct from the CI-generated `articles`.
 * Only present on sites whose site.config.js declares a `hubs` array; sites
 * without a `src/content/hubs/` directory load an empty set (glob → []), so
 * existing sites are unaffected.
 */
const hubs = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/hubs' }),
  schema: z.object({
    title: z.string().max(70),
    description: z.string().min(120).max(180),
    slug: z.string(),                       // == /<slug>/ ; guarded against intent-slug collisions at build time
    order: z.number().default(0),
    heroImage: z.string().optional(),
    heroImageAlt: z.string().optional(),
    intro: z.string().optional(),
    publishedAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    sources: z.array(sourceEntry).default([]),
    faq: z.array(faqEntry).optional(),
    relatedArticles: z.array(z.string()).default([]),
    draft: z.boolean().default(false),
  }),
});

/**
 * Satellite pages under a hub (e.g. /solaire/kit-solaire/). Full transactional
 * comparatif/avis pages, hand-authored. Mirrors the `articles` field set so the
 * shared layout + components (ComparisonTable, ProductCard, SourceList…) render
 * them identically, plus hub parenting + intra-hub mesh.
 */
const satellites = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/satellites' }),
  schema: z.object({
    title: z.string().max(70),
    description: z.string().min(120).max(180),
    keyword: z.string(),
    secondaryKeywords: z.array(z.string()).optional(),
    intent: z.enum(['avis', 'comparatif', 'guide']).default('comparatif'),
    hub: z.string(),                         // parent hub slug
    slug: z.string().optional(),             // defaults to the file id
    order: z.number().default(0),
    publishedAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    heroImage: z.string().optional(),
    heroImageAlt: z.string().optional(),
    sources: z.array(sourceEntry).min(3, 'Min 3 sources for grounding (anti scaled-content-abuse — see CLAUDE.md)'),
    affiliateLinks: z.array(affiliateLink).default([]),
    groundingScore: z.string().optional(),
    faq: z.array(faqEntry).optional(),
    // avis-style
    product: z.object({ name: z.string(), developer: z.string().optional() }).optional(),
    subscores: z.record(z.string(), z.number().min(0).max(10)).optional(),
    weights: z.record(z.string(), z.number().min(0).max(1)).optional(),
    finalScore: z.number().min(0).max(10).optional(),
    pros: z.array(z.string()).optional(),
    cons: z.array(z.string()).optional(),
    // comparatif-style
    products: z.array(productEntry).optional(),
    // intra-hub + blog mesh
    relatedSatellites: z.array(z.string()).default([]),
    relatedArticles: z.array(z.string()).default([]),
    draft: z.boolean().default(false),
  }),
});

export const collections = { articles, page, hubs, satellites };
